services:
  react:
    container_name: my_page
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: .
        target: /frontend
    ports:
      - ${REACT_PORT}:3000
    env_file:
      - dev.env
    networks:
      - default
    restart: always
    tty: true
    stdin_open: true

networks:
  default:
    name: ${USER_NAME}
    external: true
